#Noah Flores  
#z1861588 
#CSCI 340-1 
#I certify that this is my own work and where appropriate an extension  
#of the starter code provided for the assignment. 
#
binarytreeDriver.exe: binarytreeDriver.cc binarytree.h node.h
	g++ -std=c++11 -Wall -Wextra -pedantic -o binarytreeDriver.exe binarytreeDriver.cc binarytree.h node.h

clean:
	rm *.exe
