#Noah Flores  
#z1861588 
#CSCI 340-1 
#I certify that this is my own work and where appropriate an extension  
#of the starter code provided for the assignment. 
#
heap.exe: heap.cc heap.h 
	g++ -std=c++11 -g -Wall -Wextra -pedantic -o heap.exe heap.cc heap.h

clean:
	rm *.exe
