#Noah Flores  
#z1861588 
#CSCI 340-1 
#I certify that this is my own work and where appropriate an extension  
#of the starter code provided for the assignment. 
#
bstDriver.exe: bstDriver.cc bstDriver.h node.h
	g++ -std=c++11 -g -Wall -Wextra -pedantic -o bstDriver.exe bstDriver.cc bstDriver.h node.h

clean:
	rm *.exe
